### ISSUE TITLE
Inconsistencies for test_keys in middlebox tests

### ISSUE THREAD

**Issue by lorenzoPrimi** [ooni/spec#110]
I recently found out that the same json key can have a different type based on the test.
This wasn't a problem if the type was String or Boolean, but became a problem when a type could have been Object or Boolean like in this case

**http_invalid_request_line**
```
test_keys {
    tampering BOOL
}
```
**http_header_field_manipulation**

```
test_keys {
    tampering {
        header_field_name
        header_field_number
        header_field_value
        header_name_capitalization
        request_line_capitalization
        total
    }
}
```

I will keep this thread updated with every inconsistency I found, even small ones so we can decide case by case.

**Comment by lorenzoPrimi** [comment]
**Web connectivity**
`
test_keys  {
    blocking can be Bool false (test ok) or String (anomaly)
}
`
Can also be NULL (test failed) but this is not a big issue. everything can be null

**Comment by hellais** [comment]
In general we don't have any rule on how the `test_keys` for different tests should look like and inside of the specification of each test (ex. https://github.com/ooni/spec/blob/master/test-specs/ts-006-header-field-manipulation.md) you will find a description of how they should look like depending on type of test.

I would suggest you use a different, per test, data model to represent the results of each test and not assume that a key with the same name will have the same format in different tests (we never make this guarantee in the spec).

I am going to leave this open for the moment, but we will probably not be addressing this anytime soon as it will break how data is handled by the pipeline (and it will require migration scripts between the data formats).

That said, we may make some changes to improve this situation as part of: https://github.com/ooni/spec/issues/74.

**Comment by bassosimone** [comment]
I believe we should gradually migrate away from a model where something can be `null` or a specific type, as we've seen this is a pain to process it in, say, golang (and also Java).

**Comment by hellais** [comment]
> I believe we should gradually migrate away from a model where something can be null or a specific type, as we've seen this is a pain to process it in, say, golang (and also Java).

Yes I agree with this, however it's something that we can't easily address at the moment without breaking a lot of the downstream and upstream code.

I would say we should probably have a set of guidelines and principles for data formats as part of the next gen OONI Spec definition and this could be one of the points.

**Comment by bassosimone** [comment]
> I would say we should probably have a set of guidelines and principles for data formats as part of the next gen OONI Spec definition and this could be one of the points.

Sounds reasonable!

**Comment by lorenzoPrimi** [comment]
I understand that make test specific class in Java is the easiest solution for now, I also agree with your reasoning for the future as the current data format looks a bit messy and confusing to me

**Comment by bassosimone** [comment]
FTR, something being `NULL` or a type in Go is:

```Go
    Field *Type `json:"field"`
```

The main issue is when something can be `NULL`, or more than a single type.

**Comment by bassosimone** [comment]
I believe this issue is invalid in that different tests may need to express similar concepts with different concrete implementations, therefore there's no super-symmetry here. I sympathise a great deal with trying to make the data format more predictable and specifically with #74, though.
