### ISSUE TITLE
Where should I submit an issue documentation

### ISSUE THREAD

**Issue by anadahz** [ooni/spec#131]
Often is not clear which component belongs to which repository, perhaps a central repository should have all repositories with a short description.

Users would be able to consult this repository and open issues, follow development and comments accordingly.

**Comment by bassosimone** [comment]
I was about to close this issue recommending to open it in ooni/website, then it occurred to me that it's also possible to transfer issues, so I'll transfer it on your behalf.

**Comment by bassosimone** [comment]
Bummer, ooni-web is in another org. In any case, I guess we're making progress in this direction already by moving the new engine into the github.com/ooni org. Also, I recently created a description of what the OONI probe is and all the related repos. Can you perhaps [check it out](https://github.com/ooni/spec/tree/master/probe) and tell me whether it helps solving the problem that you were raising here? I'm going to meanwhile close the issue. Let's reopen it, if needed.

**Comment by anadahz** [comment]
The file in https://github.com/ooni/spec/blob/master/probe/README.md has a very neat representation of OONI's software components. 
The point of this issue is to document where one should submit an issue, for instance one submits a bug report for android probe but the issue is (quite often) relevant to the ios probe as well.

Thanks for working on this.

**Comment by bassosimone** [comment]
You're right! So, I'll reopen, see to improve a bit more, and ask for feedback again!

**Comment by hellais** [comment]
The OONI Probe mater repo has links to all the relevant OONI Probe sub-repositories: https://github.com/ooni/probe.

If in doubt just file issues in ooni/probe and we will be sure to migrate them to the relevant repository if necessary.
