### ISSUE TITLE
Implement fast-path pipeline

### ISSUE THREAD

**Issue by FedericoCeratto** [ooni/spec#145]
Currently the data processing pipeline takes ~24h for measurements to be published. We will be working to reduce this latency to less than daily.
Requirements:
- Classify measurements into categories: no blocking, ISP blocking, global blocking, network issues
- Support heuristics/weights and measure confidence
- Detect changes in blocking (required for #144)
Implement #144
Depends on #146
Soft-depends on #143 

[MVP design](http://interactive.blockdiag.com/?compression=deflate&src=eJxLyslPzk7JTExXqOZSUHDOz8lJTS7JLypW0LVTCA72cEtNTUktAnE889JTi0sy8_NAHMe8xJzK4kywqoDgQB-91LLUvBIwNyg4GKSJqxYARaMdGg)

[Final design](http://interactive.blockdiag.com/?compression=deflate&src=eJxLyslPzk7JTExXqOZSUHDOz8lJTS7JLypW0LVTCA72cEtNTUktAnE889JTi0sy8_PAMsYBiUWFpaklII5jXmJOZXEmWEtAcKCPXmpZal4JmBsUHAwyAWhysDFEHxYDgbJo2lwrCnLyi1KLuGoB1TMyHQ)

**Comment by hellais** [comment]
This is just pending deployment: https://github.com/ooni/sysadmin/issues/394
