### ISSUE TITLE
WebConnectivity: specify http://<ip>/<path> case

### ISSUE THREAD

**Issue by bassosimone** [ooni/spec#148]
The WebConnectivity specification does not say what the code is supposed to do when the input URL contains an `<ip>` rather than an `<hostname>` host. The helper is currently broken because it returns a (going on memory) `dns_name_error` error. As part of releasing MK v0.10.5, I'm setting the `dns` field to `null` because that is the most clear (and conveniently most Go friendly) indication that a specific step has been skipped.

**Comment by hellais** [comment]
We should also mention in the spec that when you measure an IP the `dns_consistency` value should be `consistent`
