### ISSUE TITLE
Create a Code of Conduct for OONI

### ISSUE THREAD

**Issue by anadahz** [ooni/spec#69]
An OONI code of conduct should be written, example: https://www.debian.org/code_of_conduct

**Comment by irl** [comment]
At the 2015 Summer Dev Meeting (according to the wiki - I wasn't there) this was discussed for the Tor project:

https://trac.torproject.org/projects/tor/wiki/org/meetings/2015SummerDevMeeting/AroundTheTorWorld/CodeOfConduct

I would suggest that OONI, as a Tor project, simply inherits anything the Tor Project implements. If this is not yet implemented, which it looks may be the case, then driving this upstream would be a good approach with wider impact.

**Comment by hellais** [comment]
Given that Tor now has a Social contract, I don't think as OONI we need to duplicate this effort and we should just point people to: https://blog.torproject.org/tor-social-contract.

I am going to close this issue as resolved.
